package minhtc.vn.transferservice.enums;

public enum TransferStatus {
    CREATED,

    OTP_PENDING,
    OTP_VERIFIED,
    OTP_FAILED,
    OTP_EXPIRED,

    SOURCE_RESERVE_PENDING,
    SOURCE_RESERVED,
    SOURCE_RESERVE_FAILED,

    TARGET_CREDIT_PENDING,
    TARGET_CREDITED,
    TARGET_CREDIT_FAILED,

    SOURCE_FINALIZE_PENDING,
    SOURCE_FINALIZED,

    COMPLETED,

    COMPENSATION_PENDING,
    COMPENSATING,
    COMPENSATED,
    COMPENSATION_FAILED,

    CANCELLED,
    FAILED,
    MANUAL_REVIEW
}
