package minhtc.vn.transferservice.enums;

public enum TransferEventType {

    TRANSFER_CREATED,

    TRANSFER_OTP_PENDING,

    TRANSFER_OTP_VERIFIED,

    TRANSFER_SOURCE_RESERVED,

    TRANSFER_TARGET_CREDITED,

    TRANSFER_COMPLETED,

    TRANSFER_COMPENSATED,

    TRANSFER_FAILED,

    TRANSFER_MANUAL_REVIEW_REQUIRED,

    TRANSFER_CANCELLED
}